name: flutter_travel_ui
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.5
  flutter_web_frame: 
    git:
      url: https://github.com/sanihaq/flutter_web_frame.git
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: AppIcons
      fonts:
       - asset: assets/fonts/AppIcons.ttf
    - family: "Playfair Display"
      fonts:
      - asset: assets/fonts/Playfair_Display/static/PlayfairDisplay-Bold.ttf
        weight: 700
    - family: Roboto
      fonts: 
      - asset: assets/fonts/Roboto/Roboto-Medium.ttf
        weight: 500
      - asset: assets/fonts/Roboto/Roboto-Regular.ttf
        weight: 400
